version: '3.8'
services:
  sql-server:
    build:
      context: ../Sql_sever
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=123
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
  app:
    build:
      context: ../
      dockerfile: Dockerfile