version: '3.8'
services:
  sql-server:
    build:
      context: ../Sql_sever
      dockerfile: Dockerfile
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=sa12345!
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    
    volumes:
      - ../Sql_sever/Data:/var/opt/mssql/data
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8081:80 
volumes:                                
    mssqlvolum:        
      name: sqlserver-xtlab-vl